config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as:'about'

resources :posts do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :delete_all
  validates :title, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



def create
@post = Post.find(params[:post_id])
@comment = @post.comments.create(comment_params)

redirect_to post_path(@post)
end

private def comment_params
  params.require(:comment).permit(:username, :body)
end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Page about Us!'
    @textabout = 'Site is just for tests'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



  def index
      @post =Post.all
  end

  def new
      @post = Post.new
  end

  def show
      @post = Post.find(params[:id])
  end

  def edit
      @post = Post.find(params[:id])
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy

      redirect_to posts_path, notice: 'Post DELETED!'

  end

  def update
      @post = Post.find(params[:id])

      if @post.update(post_params)
        redirect_to @post, notice: 'Post Updated!'
      else
        render 'edit'
      end
  end

  def create
      #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if @post.save
          redirect_to @post
        else
          render 'new'
        end
  end

  private def post_params
      params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Test-01</title>
    <!-- Кодировка веб-страницы -->
 <meta charset="utf-8">
 <!-- Настройка viewport -->
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <%= csrf_meta_tags %>
 <%= csp_meta_tag %>
 <%= javascript_importmap_tags %>

<%= javascript_include_tag "application" %>

 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-danger">
             <div class="container-fluid">

                    <a class="navbar-brand ms-4" href="/">
                       <%= image_tag("logo.png", size: "50", :alt => "") %> El Gato
                    </a>

                          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                          </button>

     <form class="d-flex">
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <ul class="navbar-nav me-4 mb-2 mb-lg-0">

                                      <li class="nav-item me-4 mb-2 mb-lg-0">
                                      <%= link_to "Main Page", home_path, class: "btn btn-outline-light text-dark"%>
                                      </li>

                                      <li class="nav-item me-4 mb-2 mb-lg-0">
                                      <%= link_to "About", about_path, class: "btn btn-outline-light text-dark"%>
                                      </li>

                                      <li class="nav-item me-4 mb-2 mb-lg-0">
                                      <%= link_to "ADD Post", new_post_path, class: "btn btn-outline-light text-dark"%>
                                      </li>

                          </ul>
                </div>

      </form>

            </div>
          </nav>


       <div class="container">
         <%= yield %>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<br>
<div class="position-absolute top-50 start-50 translate-middle">
<h4><%= @heading %></h4>
<p><%= @textabout %></p>
</div>

app/views/posts/edit.html.erb
<h2>Editing post</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <% if @post.errors.any? %>
     <% @post.errors.full_messages.each do |msg| %>
       <div class="alert">
         <%= msg %>
       </div>
     <% end %>
  <% end %>
<p>
    Name <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    Text Area <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/index.html.erb
<br>
<h2 class="text-center">All posts</h2>
<br>
<% if flash[:notice].present? %>
    <p class='mb mt alert alert-warning'><%= flash[:notice] %></p>
<% end %>

<% @post.each do |post| %>
  <div class="alert alert-dark">
      <h3><%=  post.title %></h3>
          <div class="container-fluid" style="height: 20rem;">
              <p class="overflow-hidden" style="height: 20rem;"><%=  post.body %></p>
          </div>
      <hr>
      <%= link_to "read more...", post_path(post), :class =>'btn btn-danger' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Adding new post</h2>

<%= form_for :post, url: posts_path do |f| %>

  <% if @post.errors.any? %>
     <% @post.errors.full_messages.each do |msg| %>
       <div class="alert alert-danger">
         <%= msg %>
       </div>
     <% end %>
  <% end %>
<p>
    Name <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    Text Area <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/show.html.erb
  <!-- Title -->
  <br>
  <h1 class="text-center"><%= @post.title %></h1>
  <br>

<!-- Body -->
<body>

  <div class="card">
    <div class="col-half-offset bg-dark text-white container-fluid">

      <p> <%= simple_format(@post.body) %> </p>

    </div>
  </div>

  <!-- Buttons -->
  <hr>
  <div class="alert alert-light">
    <%= link_to "Edit post", edit_post_path(@post),  class: "btn btn-outline-warning" %>

    <%= button_to 'Delete post', post_path(@post), method: :delete, 
    form: {data: {turbo_confirm: 'Are you sure?'}}, :class => "btn btn-outline-danger"%>


  </div>
  <% if flash[:notice].present? %>
  <p class='mb mt alert alert-warning'><%= flash[:notice] %></p>
  <% end %>

  <!-- Comments -->

  <hr>
  <br>
  <h3 class="text-center">All Comments</h3><br>
  <% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <h5><strong><%=  comment.username %></strong>: <%= comment.body %></h5>
  </div>
  <% end %>



  <hr>
  <br>
  <h4>Add your Comment</h4>
  <%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Username <br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    Text <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit("Add your comment", {:class => 'btn btn-success'}) %>
  </p>

  <% end %>
</body>